function showSuccessBanner(message = 'Report submitted successfully!') {
    let banner = document.getElementById('submissionSuccessBanner');
    if (!banner) { banner = document.createElement('div'); banner.id = 'submissionSuccessBanner'; banner.setAttribute('role', 'status'); banner.style.position = 'fixed'; banner.style.top = '78px'; banner.style.right = '24px'; banner.style.zIndex = '10000'; banner.style.maxWidth = '420px'; banner.style.padding = '14px 18px'; banner.style.borderRadius = '8px'; banner.style.background = 'linear-gradient(135deg, #59AF29 0%, #254911 100%)'; banner.style.color = '#fff'; banner.style.boxShadow = '0 10px 24px rgba(37, 73, 17, 0.28)'; banner.style.fontFamily = 'Inter, Segoe UI, Arial, sans-serif'; banner.style.fontSize = '14px'; banner.style.fontWeight = '700'; banner.style.lineHeight = '1.4'; banner.style.opacity = '0'; banner.style.transform = 'translateY(-10px)'; banner.style.transition = 'opacity 0.2s ease, transform 0.2s ease'; document.body.appendChild(banner); }
    banner.textContent = message; requestAnimationFrame(() => { banner.style.opacity = '1'; banner.style.transform = 'translateY(0)'; }); clearTimeout(window.submissionSuccessBannerTimer); window.submissionSuccessBannerTimer = setTimeout(() => { banner.style.opacity = '0'; banner.style.transform = 'translateY(-10px)'; }, 3500);
}
document.addEventListener('DOMContentLoaded', () => {
    const tableBody = document.querySelector('.main-table tbody');
    const columns = ['date_of_act','activities_conducted','objectives','act_status','issues_or_concerns','financial_report','recommendations','plans_for_next_months'];
    function addBlankRow(values = {}) { const row = document.createElement('tr'); columns.forEach(key => { const cell = document.createElement('td'); cell.contentEditable = 'true'; cell.innerText = values[key] || ''; row.appendChild(cell); }); tableBody.appendChild(row); }
    document.querySelector('.add-row-btn')?.addEventListener('click', () => addBlankRow());
    document.querySelector('.delete-row-btn')?.addEventListener('click', () => { if (tableBody.rows.length > 1) tableBody.deleteRow(tableBody.rows.length - 1); else alert('No rows to delete.'); });
    function collectMar() { return { type: window.reportType || 'Monthly Accomplishment Report', department: document.getElementById('department')?.value || '', month: document.getElementById('month')?.value || '', title_act: document.getElementById('title_act')?.value || '', location: document.getElementById('location')?.value || '', benefeciaries: document.getElementById('benefeciaries')?.value || '', date_submitted: document.getElementById('date_submitted')?.value || '', rows: Array.from(tableBody.rows).map(row => { const cells = row.querySelectorAll('td'); const data = {}; columns.forEach((key, index) => data[key] = cells[index]?.innerText.trim() || ''); return data; }) }; }
    function fillMar(data) { ['department','month','title_act','location','benefeciaries','date_submitted'].forEach(id => { const el = document.getElementById(id); if (el) el.value = data[id] || ''; }); tableBody.innerHTML = ''; const rows = Array.isArray(data.rows) && data.rows.length ? data.rows : [{}]; rows.forEach(addBlankRow); }
    function clearMar() { ['month','title_act','location','benefeciaries','date_submitted'].forEach(id => { const el = document.getElementById(id); if (el) el.value = ''; }); tableBody.innerHTML = ''; addBlankRow(); }
    const draftManager = ReportDrafts.create({ storageKey: 'monthly_accomplishment_report', collect: collectMar, fill: fillMar, clear: clearMar });
    draftManager.checkDatabaseDraft();
    document.querySelector('.submit-button')?.addEventListener('click', async event => { event.preventDefault(); const data = draftManager.applySubmitMeta(collectMar()); try { const response = await fetch('post.php', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || 'Submission failed.'); draftManager.completeSubmit(); showSuccessBanner(result.message || 'Report submitted successfully!'); clearMar(); } catch (error) { alert(`Error: ${error.message}`); } });
});
